const bongo = new Audio();
bongo.src = "./src/sonido/bongo.mp3";
const c= new Audio();
c.src = "./src/sonido/c.mp3";
const f= new Audio();
f.src = "./src/sonido/f.mp3";
const b= new Audio();
b.src = "./src/sonido/b.mp3";
const space= new Audio();
space.src = "./src/sonido/space.mp3";
const uno= new Audio();
uno.src ="./src/sonido/uno.mp3"
const nueve= new Audio();
nueve.src ="./src/sonido/nueve.mp3"
const cero= new Audio();
cero.src ="./src/sonido/cero.mp3"
const q= new Audio();
q.src ="./src/sonido/q.mp3"
const w= new Audio();
w.src ="./src/sonido/w.mp3"
const p= new Audio();
p.src ="./src/sonido/p.mp3"